# Emojis extracted from iMessage dataset
# Each emoji appears exactly as used in the dataset (including skin tone variants)
# Comments show usage: Me: X Them: Y

EMOJIS = [
    "👍",  # Me: 58 Them: 45
    "😂",  # Me: 0 Them: 93
    "🎉",  # Me: 43 Them: 31
    "🔥",  # Me: 51 Them: 16
    "👌",  # Me: 39 Them: 18
    "🍻",  # Me: 49 Them: 8
    "😎",  # Me: 29 Them: 20
    "😊",  # Me: 5 Them: 41
    "❤️",  # Me: 1 Them: 44
    "👍🏻",  # Me: 0 Them: 45
    "💕",  # Me: 0 Them: 44
    "👀",  # Me: 10 Them: 34
    "💰",  # Me: 38 Them: 3
    "🗿",  # Me: 36 Them: 2
    "🫡",  # Me: 16 Them: 18
    "😭",  # Me: 0 Them: 31
    "🙏",  # Me: 23 Them: 4
    "😘",  # Me: 0 Them: 25
    "😩",  # Me: 12 Them: 10
    "👋🏻",  # Me: 0 Them: 21
    "😐",  # Me: 13 Them: 7
    "🤠",  # Me: 16 Them: 4
    "😬",  # Me: 11 Them: 9
    "💓",  # Me: 0 Them: 19
    "🏆",  # Me: 7 Them: 12
    "👍🏼",  # Me: 0 Them: 19
    "🇺🇸",  # Me: 16 Them: 2
    "🙄",  # Me: 6 Them: 12
    "🤣",  # Me: 0 Them: 18
    "😔",  # Me: 0 Them: 17
    "🎂",  # Me: 10 Them: 7
    "💯",  # Me: 6 Them: 9
    "☺️",  # Me: 5 Them: 9
    "♀️",  # Me: 1 Them: 13
    "👏🏻",  # Me: 0 Them: 14
    "🤌",  # Me: 1 Them: 13
    "💪",  # Me: 11 Them: 2
    "🥰",  # Me: 2 Them: 11
    "🤓",  # Me: 11 Them: 2
    "😱",  # Me: 2 Them: 10
    "🍾",  # Me: 9 Them: 3
    "✨",  # Me: 8 Them: 4
    "🤘",  # Me: 6 Them: 5
    "🎄",  # Me: 8 Them: 3
    "👋",  # Me: 10 Them: 1
    "🙂",  # Me: 0 Them: 11
    "♂️",  # Me: 7 Them: 4
    "😁",  # Me: 0 Them: 10
    "🙌",  # Me: 0 Them: 10
    "👋🏼",  # Me: 0 Them: 9
    "🕺",  # Me: 2 Them: 7
    "👏",  # Me: 2 Them: 7
    "🤝",  # Me: 6 Them: 3
    "📈",  # Me: 9 Them: 0
    "🚩",  # Me: 6 Them: 2
    "😢",  # Me: 3 Them: 5
    "🤙",  # Me: 3 Them: 5
    "🤔",  # Me: 5 Them: 3
    "😳",  # Me: 3 Them: 5
    "✈️",  # Me: 1 Them: 7
    "🥳",  # Me: 2 Them: 5
    "🤗",  # Me: 0 Them: 7
    "🦅",  # Me: 6 Them: 1
    "💀",  # Me: 1 Them: 6
    "☀️",  # Me: 2 Them: 5
    "💩",  # Me: 7 Them: 0
    "🚨",  # Me: 3 Them: 4
    "☹️",  # Me: 2 Them: 5
    "👌🏻",  # Me: 0 Them: 7
    "🥴",  # Me: 6 Them: 1
    "🦃",  # Me: 5 Them: 2
    "👌🏼",  # Me: 0 Them: 6
    "😃",  # Me: 2 Them: 4
    "😑",  # Me: 1 Them: 5
    "💦",  # Me: 3 Them: 3
    "😍",  # Me: 0 Them: 6
    "😅",  # Me: 0 Them: 6
    "💗",  # Me: 0 Them: 6
    "☠️",  # Me: 1 Them: 5
    "🍀",  # Me: 2 Them: 4
    "🤪",  # Me: 1 Them: 4
    "🎁",  # Me: 2 Them: 3
    "🥂",  # Me: 0 Them: 5
    "😵",  # Me: 2 Them: 3
    "😤",  # Me: 2 Them: 3
    "🎈",  # Me: 2 Them: 3
    "🤷🏻",  # Me: 0 Them: 5
    "💜",  # Me: 0 Them: 5
    "🚀",  # Me: 3 Them: 2
    "🎅🏿",  # Me: 5 Them: 0
    "💛",  # Me: 0 Them: 5
    "😴",  # Me: 0 Them: 5
    "🔫",  # Me: 2 Them: 3
    "😕",  # Me: 3 Them: 1
    "🤷",  # Me: 3 Them: 1
    "🤐",  # Me: 4 Them: 0
    "⚡️",  # Me: 3 Them: 1
    "🤍",  # Me: 0 Them: 4
    "😉",  # Me: 2 Them: 2
    "✅",  # Me: 2 Them: 2
    "👉",  # Me: 3 Them: 1
    "💎",  # Me: 1 Them: 3
    "🤢",  # Me: 1 Them: 3
    "🌶️",  # Me: 0 Them: 4
    "💙",  # Me: 0 Them: 4
    "🙏🏼",  # Me: 0 Them: 4
    "👈",  # Me: 3 Them: 1
    "🤞",  # Me: 1 Them: 3
    "👍🏾",  # Me: 0 Them: 4
    "😄",  # Me: 3 Them: 1
    "🎃",  # Me: 3 Them: 1
    "🥺",  # Me: 1 Them: 3
    "😞",  # Me: 2 Them: 2
    "✌",  # Me: 1 Them: 3
    "🫶🏼",  # Me: 0 Them: 4
    "💥",  # Me: 3 Them: 0
    "🥲",  # Me: 0 Them: 3
    "🌙",  # Me: 0 Them: 3
    "🗣",  # Me: 3 Them: 0
    "🗽",  # Me: 1 Them: 2
    "🌲",  # Me: 3 Them: 0
    "🐒",  # Me: 3 Them: 0
    "😏",  # Me: 2 Them: 1
    "🙌🏼",  # Me: 0 Them: 3
    "💡",  # Me: 3 Them: 0
    "🦬",  # Me: 2 Them: 1
    "🤷🏽",  # Me: 0 Them: 3
    "😆",  # Me: 0 Them: 3
    "⛷️",  # Me: 3 Them: 0
    "🐕",  # Me: 3 Them: 0
    "💔",  # Me: 0 Them: 3
    "🐥",  # Me: 0 Them: 3
    "💤",  # Me: 0 Them: 3
    "🧐",  # Me: 2 Them: 1
    "👨",  # Me: 2 Them: 1
    "😜",  # Me: 0 Them: 3
    "☝️",  # Me: 3 Them: 0
    "😋",  # Me: 0 Them: 3
    "🏼",  # Me: 0 Them: 3
    "🐸",  # Me: 2 Them: 1
    "🐶",  # Me: 3 Them: 0
    "😫",  # Me: 3 Them: 0
    "✊",  # Me: 3 Them: 0
    "😡",  # Me: 2 Them: 1
    "📸",  # Me: 1 Them: 2
    "🙁",  # Me: 1 Them: 2
    "✌️",  # Me: 2 Them: 1
    "😮",  # Me: 1 Them: 1
    "✋",  # Me: 2 Them: 0
    "👋🏽",  # Me: 0 Them: 2
    "🎅🏾",  # Me: 2 Them: 0
    "🥹",  # Me: 1 Them: 1
    "🐯",  # Me: 2 Them: 0
    "🍺",  # Me: 1 Them: 1
    "💪🏼",  # Me: 0 Them: 2
    "🤯",  # Me: 1 Them: 1
    "👎",  # Me: 1 Them: 1
    "🤌🏼",  # Me: 0 Them: 2
    "🔋",  # Me: 2 Them: 0
    "🙃",  # Me: 1 Them: 1
    "🚉",  # Me: 1 Them: 1
    "🚊",  # Me: 1 Them: 1
    "🇨🇦",  # Me: 1 Them: 1
    "🌟",  # Me: 1 Them: 1
    "🤙🏼",  # Me: 0 Them: 2
    "😀",  # Me: 0 Them: 2
    "⚔️",  # Me: 0 Them: 2
    "😈",  # Me: 1 Them: 1
    "🔒",  # Me: 1 Them: 1
    "🤨",  # Me: 1 Them: 1
    "🎶",  # Me: 0 Them: 2
    "📉",  # Me: 2 Them: 0
    "🙈",  # Me: 0 Them: 2
    "🍸",  # Me: 2 Them: 0
    "🏃",  # Me: 1 Them: 1
    "❄️",  # Me: 2 Them: 0
    "☕️",  # Me: 1 Them: 1
    "💸",  # Me: 2 Them: 0
    "😧",  # Me: 2 Them: 0
    "👭",  # Me: 2 Them: 0
    "🚗",  # Me: 2 Them: 0
    "⛹️",  # Me: 2 Them: 0
    "🛰",  # Me: 2 Them: 0
    "🏝",  # Me: 2 Them: 0
    "💫",  # Me: 1 Them: 1
    "🍕",  # Me: 2 Them: 0
    "🫖",  # Me: 1 Them: 0
    "👷",  # Me: 1 Them: 0
    "🪝",  # Me: 1 Them: 0
    "🐐",  # Me: 1 Them: 0
    "🌍",  # Me: 0 Them: 1
    "🫦",  # Me: 0 Them: 1
    "🐼",  # Me: 1 Them: 0
    "🇯🇵",  # Me: 0 Them: 1
    "🌱",  # Me: 0 Them: 1
    "🥜",  # Me: 1 Them: 0
    "🧟",  # Me: 1 Them: 0
    "👴",  # Me: 1 Them: 0
    "🐷",  # Me: 1 Them: 0
    "😓",  # Me: 0 Them: 1
    "🇫🇷",  # Me: 1 Them: 0
    "☹",  # Me: 0 Them: 1
    "🤒",  # Me: 0 Them: 1
    "🪐",  # Me: 0 Them: 1
    "👫",  # Me: 1 Them: 0
    "🌖",  # Me: 1 Them: 0
    "🖤",  # Me: 0 Them: 1
    "🤬",  # Me: 1 Them: 0
    "✍",  # Me: 0 Them: 1
    "😦",  # Me: 1 Them: 0
    "🕵️",  # Me: 0 Them: 1
    "⚠️",  # Me: 1 Them: 0
    "🔭",  # Me: 1 Them: 0
    "🍨",  # Me: 0 Them: 1
    "🛳",  # Me: 1 Them: 0
    "🐱",  # Me: 1 Them: 0
    "💺",  # Me: 1 Them: 0
    "💅",  # Me: 0 Them: 1
    "🤦🏻",  # Me: 0 Them: 1
    "🍣",  # Me: 1 Them: 0
    "🙏🏻",  # Me: 0 Them: 1
    "🤘🏼",  # Me: 0 Them: 1
    "🫨",  # Me: 1 Them: 0
    "🧊",  # Me: 0 Them: 1
    "💨",  # Me: 1 Them: 0
    "🙋🏼",  # Me: 0 Them: 1
    "🔮",  # Me: 1 Them: 0
    "🚇",  # Me: 1 Them: 0
    "🏀",  # Me: 0 Them: 1
    "🚂",  # Me: 1 Them: 0
    "😒",  # Me: 0 Them: 1
    "💼",  # Me: 1 Them: 0
    "💪🏻",  # Me: 0 Them: 1
    "🇲🇽",  # Me: 0 Them: 1
    "👏🏼",  # Me: 0 Them: 1
    "🥞",  # Me: 1 Them: 0
    "😶",  # Me: 0 Them: 1
    "⚕️",  # Me: 1 Them: 0
    "😚",  # Me: 0 Them: 1
    "🏈",  # Me: 1 Them: 0
    "🌏",  # Me: 0 Them: 1
    "🍋",  # Me: 0 Them: 1
    "🍑",  # Me: 1 Them: 0
    "🎢",  # Me: 1 Them: 0
    "🫱",  # Me: 0 Them: 1
    "🏾",  # Me: 0 Them: 1
    "🤕",  # Me: 1 Them: 0
    "🤮",  # Me: 1 Them: 0
    "🤡",  # Me: 0 Them: 1
    "🎯",  # Me: 1 Them: 0
    "🧀",  # Me: 1 Them: 0
    "💁🏽",  # Me: 0 Them: 1
    "🦠",  # Me: 0 Them: 1
    "🐘",  # Me: 1 Them: 0
    "🍳",  # Me: 0 Them: 1
    "💃🏻",  # Me: 0 Them: 1
    "🔪",  # Me: 1 Them: 0
    "🥣",  # Me: 0 Them: 1
    "🥯",  # Me: 1 Them: 0
    "🐮",  # Me: 1 Them: 0
    "🖐",  # Me: 1 Them: 0
    "💣",  # Me: 0 Them: 1
    "🤦",  # Me: 0 Them: 1
    "🤴",  # Me: 1 Them: 0
    "🎸",  # Me: 0 Them: 1
    "👻",  # Me: 0 Them: 1
    "🫠",  # Me: 0 Them: 1
    "😯",  # Me: 0 Them: 1
    "🏭",  # Me: 1 Them: 0
    "🔜",  # Me: 1 Them: 0
    "🌊",  # Me: 1 Them: 0
    "🥷",  # Me: 1 Them: 0
    "🌞",  # Me: 0 Them: 1
    "🦉",  # Me: 1 Them: 0
    "👬",  # Me: 0 Them: 1
    "🌛",  # Me: 1 Them: 0
    "💁",  # Me: 0 Them: 1
    "😖",  # Me: 0 Them: 1
    "🍞",  # Me: 1 Them: 0
    "🛑",  # Me: 1 Them: 0
    "🧖",  # Me: 1 Them: 0
    "🍉",  # Me: 1 Them: 0
    "🍵",  # Me: 1 Them: 0
    "🍁",  # Me: 1 Them: 0
    "🐻",  # Me: 1 Them: 0
    "👑",  # Me: 0 Them: 1
    "✔️",  # Me: 1 Them: 0
    "😛",  # Me: 0 Them: 1
    "🚙",  # Me: 0 Them: 1
    "🎾",  # Me: 1 Them: 0
    "👍🏿",  # Me: 1 Them: 0
    "🐎",  # Me: 0 Them: 1
    "☃️",  # Me: 0 Them: 1
    "🦇",  # Me: 0 Them: 1
    "🎅",  # Me: 1 Them: 0
    "🎱",  # Me: 1 Them: 0
    "🦖",  # Me: 1 Them: 0
    "🤞🏼",  # Me: 0 Them: 1
    "👵",  # Me: 1 Them: 0
    "🧍",  # Me: 1 Them: 0
    "✔",  # Me: 1 Them: 0
    "🏋🏻",  # Me: 0 Them: 1
    "🕰",  # Me: 1 Them: 0
    "💵",  # Me: 0 Them: 1
    "🌚",  # Me: 0 Them: 1
    "🚲",  # Me: 1 Them: 0
    "🥖",  # Me: 1 Them: 0
    "😟",  # Me: 0 Them: 1
    "🤦🏽",  # Me: 0 Them: 1
    "🖕🏻",  # Me: 0 Them: 1
    "🦫",  # Me: 1 Them: 0
    "😠",  # Me: 1 Them: 0
    "📚",  # Me: 1 Them: 0
    "💧",  # Me: 1 Them: 0
    "🐈",  # Me: 0 Them: 1
    "🤏",  # Me: 1 Them: 0
    "🏿",  # Me: 1 Them: 0
    "👊🏻",  # Me: 0 Them: 1
    "🦍",  # Me: 1 Them: 0
    "🩵",  # Me: 0 Them: 1
    "👌🏽",  # Me: 0 Them: 1
    "🌫️",  # Me: 0 Them: 1
    "⛔️",  # Me: 1 Them: 0
    "♊️",  # Me: 0 Them: 1
    "📊",  # Me: 1 Them: 0
    "🌯",  # Me: 0 Them: 1
    "🎵",  # Me: 0 Them: 1
    "🤖",  # Me: 1 Them: 0
    "🩷",  # Me: 1 Them: 0
    "🤟🏼",  # Me: 0 Them: 1
    "🍤",  # Me: 0 Them: 1
    "🏠",  # Me: 0 Them: 1
    "🛡",  # Me: 1 Them: 0
    "🍹",  # Me: 1 Them: 0
    "🍎",  # Me: 0 Them: 1
    "🌎",  # Me: 0 Them: 1
    "🐉",  # Me: 1 Them: 0
    "🤩",  # Me: 1 Them: 0
    "🧙🏼",  # Me: 0 Them: 1
    "🍰",  # Me: 0 Them: 1
    "🤚",  # Me: 1 Them: 0
    "🛏️",  # Me: 1 Them: 0
    "🫲",  # Me: 0 Them: 1
    "😪",  # Me: 0 Them: 1
    "🎩",  # Me: 1 Them: 0
]
